// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

namespace TravelApi.Solutions.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    partial class TravelApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ReviewId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Author = "James",
                            City = "Bangkok",
                            Country = "Thailand",
                            Description = "lorem ipsum afdfadsfdsf",
                            Rating = 3,
                            Title = "Best city "
                        },
                        new
                        {
                            ReviewId = 2,
                            Author = "Mike",
                            City = "Paris",
                            Country = "France",
                            Description = "Lorem ipsum jklf;dajfl;adjfkl;djfklads;jf",
                            Rating = 1,
                            Title = "Worst city"
                        },
                        new
                        {
                            ReviewId = 4,
                            Author = "Shaun",
                            City = "Tokyo",
                            Country = "Japan",
                            Description = "dklfajskfl;ajdk kdfal; jfk kl;adj fka;",
                            Rating = 4,
                            Title = "A city"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
